# Modern Personality makefile for KERNEL 1.03
# Requires: 
#		MASM 4.0 (1985)
#		Microsoft C 4.0 (1986)
#		Microsoft LINK ("Overlay Linker") 3.51
# 		Microsoft Link4 ("Segmented-Executable Linker") 5.00.12

#
# | | | KERNSTUB | | |
# yes the build output is in the kernel folder
# Run from \bin

MASMARGS = MASM -I..\libw\INC -I..\kernel
SRC = ..\kernel

# Kernstub and boot stuff first
# TODO: convert to c
KERNSTUB.OBJ:	$(SRC)\KERNSTUB.ASM
	$(MASMARGS) $(SRC)\KERNSTUB.ASM KERNSTUB.OBJ,,,

KDATA.OBJ: 		$(SRC)\KDATA.ASM
	$(MASMARGS) $(SRC)\KDATA.ASM KDATA.OBJ,,,

LDBOOT.OBJ: 	$(SRC)\LDBOOT.ASM
	$(MASMARGS) $(SRC)\LDBOOT.ASM LDBOOT.OBJ,,,

DOSINIT.OBJ: 	$(SRC)\DOSINIT.ASM
	$(MASMARGS) $(SRC)\DOSINIT.ASM DOSINIT.OBJ,,,

LDFASTB.OBJ: 	$(SRC)\LDFASTB.ASM
	$(MASMARGS) $(SRC)\LDFASTB.ASM LDFASTB.OBJ,,,

LSTRING.OBJ: 	$(SRC)\LSTRING.ASM
	$(MASMARGS) $(SRC)\LSTRING.ASM LSTRING.OBJ,,,

RIP.OBJ: 		$(SRC)\RIP.C.ASM
	$(MASMARGS) $(SRC)\RIP.C.ASM RIP.OBJ,,,

DISKIO.OBJ: 	$(SRC)\DISKIO.ASM
	$(MASMARGS) $(SRC)\DISKIO.ASM DISKIO.OBJ,,,

LD.OBJ: 		$(SRC)\LD.C.ASM
	$(MASMARGS) $(SRC)\LD.C.ASM LD.OBJ,,,

TASK.OBJ: 		$(SRC)\TASK.ASM
	$(MASMARGS) $(SRC)\TASK.ASM TASK.OBJ,,,

SCHEDULE.OBJ: 	$(SRC)\SCHEDULE.ASM
	$(MASMARGS) $(SRC)\SCHEDULE.ASM SCHEDULE.OBJ,,,

CONTEXT.OBJ: 	$(SRC)\CONTEXT.ASM
	$(MASMARGS) $(SRC)\CONTEXT.ASM CONTEXT.OBJ,,,

INT21.OBJ: 		$(SRC)\INT21.ASM
	$(MASMARGS) $(SRC)\INT21.ASM INT21.OBJ,,,

I21MEM.OBJ: 		$(SRC)\I21MEM.ASM
	$(MASMARGS) $(SRC)\I21MEM.ASM I21MEM.OBJ,,,

INT24.OBJ: 		$(SRC)\INT24.ASM
	$(MASMARGS) $(SRC)\INT24.ASM INT24.OBJ,,,

HANDLE.OBJ: 	$(SRC)\HANDLE.ASM
	$(MASMARGS) $(SRC)\HANDLE.ASM HANDLE.OBJ,,,

# Global alloc
GALLOC.OBJ: 	$(SRC)\GALLOC.ASM
	$(MASMARGS) $(SRC)\GALLOC.ASM GALLOC.OBJ,,,

GCOMPACT.OBJ: 	$(SRC)\GCOMPACT.ASM
	$(MASMARGS) $(SRC)\GCOMPACT.ASM GCOMPACT.OBJ,,,

GINTERF.OBJ: 	$(SRC)\GINTERF.ASM
	$(MASMARGS) $(SRC)\GINTERF.ASM GINTERF.OBJ,,,

GLRU.OBJ: 		$(SRC)\GLRU.ASM
	$(MASMARGS) $(SRC)\GLRU.ASM GLRU.OBJ,,,

GMEM.OBJ: 		$(SRC)\GMEM.ASM
	$(MASMARGS) $(SRC)\GMEM.ASM GMEM.OBJ,,,

LALLOC.OBJ: 	$(SRC)\LALLOC.ASM
	$(MASMARGS) $(SRC)\LALLOC.ASM LALLOC.OBJ,,,

LCOMPACT.OBJ: 	$(SRC)\LCOMPACT.ASM
	$(MASMARGS) $(SRC)\LCOMPACT.ASM LCOMPACT.OBJ,,,

LINTERF.OBJ: 	$(SRC)\LINTERF.ASM
	$(MASMARGS) $(SRC)\LINTERF.ASM LINTERF.OBJ,,,

# Other load stuff

LDAUX.OBJ: 		$(SRC)\LDAUX.ASM
	$(MASMARGS) $(SRC)\LDAUX.ASM LDAUX.OBJ,,,

LDDEBUG.OBJ: 	$(SRC)\LDDEBUG.ASM
	$(MASMARGS) $(SRC)\LDDEBUG.ASM LDDEBUG.OBJ,,,

LDDISK.OBJ: 	$(SRC)\LDDISK.ASM
	$(MASMARGS) $(SRC)\LDDISK.ASM LDDISK.OBJ,,,

LDFILE.OBJ: 	$(SRC)\LDFILE.ASM
	$(MASMARGS) $(SRC)\LDFILE.ASM LDFILE.OBJ,,,

LDHEADER.OBJ: 	$(SRC)\LDHEADER.ASM
	$(MASMARGS) $(SRC)\LDHEADER.ASM LDHEADER.OBJ,,,

LDINT.OBJ: 	$(SRC)\LDINT.ASM
	$(MASMARGS) $(SRC)\LDINT.ASM LDINT.OBJ,,,

LDOPEN.OBJ: 	$(SRC)\LDOPEN.ASM
	$(MASMARGS) $(SRC)\LDOPEN.ASM LDOPEN.OBJ,,,

LDRELOC.OBJ: 	$(SRC)\LDRELOC.ASM
	$(MASMARGS) $(SRC)\LDRELOC.ASM LDRELOC.OBJ,,,

LDSEG.OBJ: 		$(SRC)\LDSEG.ASM
	$(MASMARGS) $(SRC)\LDSEG.ASM LDSEG.OBJ,,,

LDSTACK.OBJ: 	$(SRC)\LDSTACK.ASM
	$(MASMARGS) $(SRC)\LDSTACK.ASM LDSTACK.OBJ,,,

LDUTIL.OBJ: 	$(SRC)\LDUTIL.ASM
	$(MASMARGS) $(SRC)\LDUTIL.ASM LDUTIL.OBJ,,,

RESMAN.OBJ: 	$(SRC)\RESMAN.C.ASM
	$(MASMARGS) $(SRC)\RESMAN.C.ASM RESMAN.OBJ,,,

RESAUX.OBJ: 	$(SRC)\RESAUX.ASM
	$(MASMARGS) $(SRC)\RESAUX.ASM RESAUX.OBJ,,,

ATOM.OBJ: 	$(SRC)\ATOM.ASM
	$(MASMARGS) $(SRC)\ATOM.ASM ATOM.OBJ,,,

USERPRO.OBJ: 	$(SRC)\USERPRO.ASM
	$(MASMARGS) $(SRC)\USERPRO.ASM USERPRO.OBJ,,,

KDATAEND.OBJ: 	$(SRC)\KDATAEND.ASM
	$(MASMARGS) $(SRC)\KDATAEND.ASM KDATAEND.OBJ,,,

# This needs to be split, due to the maximum size of macros in MASM 4
OBJ = 	KERNSTUB.OBJ 	\
		KDATA.OBJ		\
		LDBOOT.OBJ		\
		DOSINIT.OBJ		\
		LDFASTB.OBJ		\
		RIP.OBJ			\
		DISKIO.OBJ		\
		LD.OBJ			\
		TASK.OBJ		\
		CONTEXT.OBJ		\
		INT21.OBJ		\
		I21MEM.OBJ		\
		INT24.OBJ		\
		HANDLE.OBJ		\
		GALLOC.OBJ		\
		GCOMPACT.OBJ	\
		GINTERF.OBJ		\
		GLRU.OBJ		\
		GMEM.OBJ		\
		LALLOC.OBJ		\
		LCOMPACT.OBJ	

OBJ2 =	LINTERF.OBJ		\
		LDAUX.OBJ		\
		LDBOOT.OBJ		\
		LDDEBUG.OBJ		\
		LDDISK.OBJ		\
		LDFILE.OBJ		\
		LDHEADER.OBJ	\
		LDINT.OBJ		\
		LDOPEN.OBJ		\
		LDRELOC.OBJ		\
		LDSEG.OBJ		\
		LDSTACK.OBJ		\
		LDUTIL.OBJ		\
		RESMAN.OBJ		\
		RESAUX.OBJ		\
		ATOM.OBJ		\
		USERPRO.OBJ		\

# This crappy linker can't change the output folder!!
KERNSTUB.EXE: KERNSTUB.OBJ
	LINK351 /HIGH KERNSTUB.OBJ,KERNSTUB.EXE,KERNSTUB.MAP,,

KERNEL.EXE: $(OBJ) $(OBJ2)
	LINK4 @$(SRC)\KERNEL.LNK
